spring:  
  datasource:
      url:  jdbc:postgresql://192.168.6.121:5432/dev
      username: "{cipher}d30700b168278385d7f525291a05b7d1db8307bebb63b90484fcf334f28ce92d"
      password: "{cipher}5ca273623c13e8d176907c698e529d282b61ed2267e96cce65ffc63305a49d70"
      class: com.mysql.jdbc.Driver
      
logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'

email:
  smtp: smtp.host
  smtpPort: 25
  user: user
  password: pass
  ssl: false

serverid: LOCALHOST
showalltasks: true
snapshotallowed: true
usehotandcold: true
folders:
  rootpath: E:/dreamgenics/dreampipe
  homepath: E:/dreamgenics/dreampipe/jobs
  coldpath: E:/dreamgenics/dreampipe/jobs_cold
  pipepath: E:/dreamgenics/dreampipe/lib
  taskTempPathSuffix: taskLoaderTempFolder
  
# admin panel
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/