spring:  
  datasource:
      url:  jdbc:postgresql://192.168.6.121:5432/dev
      username: "{cipher}d30700b168278385d7f525291a05b7d1db8307bebb63b90484fcf334f28ce92d"
      password: "{cipher}5ca273623c13e8d176907c698e529d282b61ed2267e96cce65ffc63305a49d70"
      class: com.mysql.jdbc.Driver
      
logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'

# Expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Obtain registry from eureka
eureka:
  client:
    fetchRegistry: true        

# GENOMEONE ENVS
address:
  zuul: http://localhost:9080/

email:
  smtp: smtp.host
  smtpport: 25
  user: user
  password: pass
  ssl: false

mindiskfreespacepercent: 10
usehttps: false
serverid: LOCALHOST
showalltasks: true
snapshotallowed: true
usehotandcold: true
folders:
  rootpath: E:/dreamgenics/dreampipe
  homepath: E:/dreamgenics/dreampipe/jobs
  coldpath: E:/dreamgenics/dreampipe/jobs_cold
  pipepath: E:/dreamgenics/dreampipe/lib
  datapath: E:/dreamgenics/data   
  tasktemppathsuffix: taskLoaderTempFolder
  relativeparentpaths: ../input,../param,.
filechooser:
  filterbyusergroups: true