# HTTP Server
server:  
  port: 8761

# Eureka not registry in other eureka server
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10  # Included for admin
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:#{server.port}/eureka  # Default eureka zone

# Distinct context for admin panel
spring:
  boot:
   admin:
     context-path: /admin 