# Spring properties
spring:
  application:
    name: zuul
  datasource:
    url:  jdbc:postgresql://192.168.6.121:5432/users
    username: "{cipher}d30700b168278385d7f525291a05b7d1db8307bebb63b90484fcf334f28ce92d"
    password: "{cipher}5ca273623c13e8d176907c698e529d282b61ed2267e96cce65ffc63305a49d70"
    class: com.mysql.jdbc.Driver
      
# the default port used for zuul service
server:
  port: 9080 
#  ssl:
#    key-store-type : PKCS12 # The format used for the keystore 
#    key-store: classpath:keystore/keystore.p12 # The path to the keystore containing the certificate
#    key-store-password: toor_Dreamgenics # The password used to generate the certificate
#    key-alias: tomcat # The alias mapped to the certificate
    
#security:
#  require-ssl: true #Since we are using Spring Security enabled application, let's configure it to accept only HTTPS requests

zuul:
  # Pass Authorization header downstream
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    authorities:
      serviceId: AUTHORITIES
      path: /authorities/**
    dreampipe-test:
      serviceId: DREAMPIPE-TEST
      path: /dreampipe-test/**
    dreampipe-jobs:
      serviceId: DREAMPIPE-JOBS
      path: /dreampipe-jobs/**

# Lets zuuls ribbon get eureka's WS list
eureka:
    client:
        fetchRegistry: true
        
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
                    
# Eureka interface with Ribbon must be disabled so Ribbon will use the list of servers indicated below
# ribbon: 
#   ReadTimeout: 10000
#   eureka:
#     enabled: false

# Above is the list of servers and ports where the different instances of the service is deployed, so Ribbon can use them for load balancing
# authorities:
#   ribbon:
# listOfServers: http://localhost:3340
# project-management:
#   ribbon:
# listOfServers: http://localhost:8040
    
app:
  serviceurl: http://localhost:8080/login/cas
  serviceticketvalidator: https://sso.dreamgenics.com/cas
  serviceauthenticationentrypoint: https://sso.dreamgenics.com/cas/login